name: Ruby
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install --jobs $(nproc)
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
